update public.verified_events
set
  start_date = '2026-03-05T19:00:00-05:00',
  date_label = 'March 5-8, 2026 - completed',
  price = 'Completed',
  ticket_requirement = 'The 2026 staging has passed; keep unpublished until new dates are verified.',
  description = 'The 2026 Jamaica Food and Drink Festival ran March 5-8 in Kingston.',
  is_published = false,
  updated_at = now()
where id = 'jamaica-food-drink-kingston';

update public.verified_events
set
  ticket_requirement = 'Keep unpublished until the official 2026 Grand Gala access details are released.',
  is_published = false,
  updated_at = now()
where id = 'grand-gala-kingston';

update public.verified_events
set
  date_label = 'Annual Emancipendence season - confirm 2026 dates',
  ticket_requirement = 'Keep unpublished until the 2026 Denbigh dates and admission details are formally announced.',
  is_published = false,
  updated_at = now()
where id = 'denbigh-agricultural-show';

insert into public.verified_events (
  id,
  title,
  city,
  region,
  parish,
  venue,
  start_date,
  date_label,
  vibes,
  price,
  ticket_requirement,
  official_url,
  description,
  source_label,
  is_published
) values
  (
    'jaaa-championships-kingston-2026',
    'JAAA/Puma National Junior and Senior Championships',
    'Kingston',
    'Kingston',
    'Kingston',
    'National Stadium',
    '2026-06-18T17:00:00-05:00',
    'June 18-21, 2026',
    array['sport', 'culture'],
    'Ticket/registration required',
    'Athlete registration and entry fees apply; spectator tickets or access should be confirmed with Athletics Jamaica or the National Stadium.',
    'https://athleticsja.org/national-championships/',
    'Jamaica Athletics national trials featuring junior and senior track and field athletes at the National Stadium.',
    'Verified island calendar',
    true
  ),
  (
    'dream-weekend-mobay-2026',
    'Dream Weekend',
    'Montego Bay',
    'North Coast',
    'St. James',
    'Montego Bay event venues',
    '2026-07-30T18:00:00-05:00',
    'July 30-August 3, 2026',
    array['music', 'nightlife'],
    'Ticket/pass required',
    'Official Dream Weekend parties require event tickets, weekend passes, or package access; confirm tiers with the organizer.',
    'https://dreamwknd.com/',
    'Multi-day party series with dancehall, soca, hip hop, DJs, and premium nightlife experiences in Montego Bay.',
    'Verified island calendar',
    true
  ),
  (
    'mobay-jerk-food-festival-2026',
    'MoBay Jerk and Food Festival',
    'Montego Bay',
    'North Coast',
    'St. James',
    'Catherine Hall Entertainment Complex',
    '2026-08-01T12:00:00-05:00',
    'August 1, 2026',
    array['food', 'family'],
    'Ticket/pass likely',
    'Festival admission, parking, VIP, or vendor experiences may require a ticket or pass; confirm with the organizer before going.',
    'https://montegobayjerkfestival.com/',
    'Montego Bay food festival focused on jerk cuisine, live entertainment, vendors, and family-friendly island culture.',
    'Verified island calendar',
    true
  ),
  (
    'best-weekend-ever-ochi-2026',
    'Best Weekend Ever',
    'Ocho Rios',
    'North Coast',
    'St. Ann',
    'Ocho Rios event venues',
    '2026-08-06T18:00:00-05:00',
    'August 6-10, 2026',
    array['music', 'nightlife'],
    'Ticket/pass required',
    'Individual parties and weekend packages require tickets or passes; confirm each event entry requirement with the organizer.',
    'https://yourbestweekendever.com/',
    'Independence Weekend event series in Ocho Rios with parties, beach events, brunches, DJs, and premium nightlife.',
    'Verified island calendar',
    true
  ),
  (
    'animecom-fest-kingston-2026',
    'AnimeCom Fest',
    'Kingston',
    'Kingston',
    'St. Andrew',
    'Kingston event venue',
    '2026-08-15T10:00:00-05:00',
    'August 15-16, 2026',
    array['culture', 'family'],
    'Ticket/pass likely',
    'Convention entry, premium access, vendor areas, or competitions may require a ticket or registration.',
    'https://www.animecomfest.com/',
    'Anime, cosplay, gaming, comics, panels, vendors, and pop-culture programming in Kingston.',
    'Verified island calendar',
    true
  ),
  (
    'jamaica-bridal-expo-kingston-2026',
    'Jamaica Bridal Expo',
    'Kingston',
    'Kingston',
    'St. Andrew',
    'Kingston event venue',
    '2026-09-12T10:00:00-05:00',
    'September 12, 2026',
    array['romance', 'culture'],
    'Registration/ticket likely',
    'Expo entry, vendor access, or trade registration may require a ticket, pass, or registration.',
    'https://www.jamaicabridalexpo.com/',
    'Wedding and romance travel expo connecting couples, planners, resorts, vendors, and travel professionals.',
    'Verified island calendar',
    true
  ),
  (
    'republic-weekend-ochi-2026',
    'Republic Weekend',
    'Ocho Rios',
    'North Coast',
    'St. Ann',
    'Ocho Rios event venues',
    '2026-10-16T21:00:00-05:00',
    'October 16-19, 2026',
    array['music', 'nightlife'],
    'Ticket/pass required',
    'Weekend passes and individual event tickets are required; some events include food or drinks while others use paid bars.',
    'https://republicweekend.com/',
    'Heroes Weekend event series in Ocho Rios with multiple themed parties, beach events, and nightlife experiences.',
    'Verified island calendar',
    true
  ),
  (
    'treasure-beach-food-rum-reggae-2026',
    'Treasure Beach Food, Rum and Reggae Festival',
    'Treasure Beach',
    'South Coast',
    'St. Elizabeth',
    'Treasure Beach community venues',
    '2026-11-06T16:00:00-05:00',
    'November 6-8, 2026',
    array['food', 'music'],
    'Ticket/pass likely',
    'Festival entry, tastings, shows, or special experiences may require tickets or passes; confirm with the organizer.',
    'https://www.foodrumreggaefestival.com/',
    'South Coast festival built around Jamaican food, rum, reggae, community energy, and Treasure Beach hospitality.',
    'Verified island calendar',
    true
  ),
  (
    'jamaica-pro-am-mobay-2026',
    'Jamaica Pro-Am Annie''s Revenge Golf Invitational',
    'Montego Bay',
    'North Coast',
    'St. James',
    'Half Moon, Cinnamon Hill, and White Witch courses',
    '2026-11-18T08:00:00-05:00',
    'November 18-22, 2026',
    array['sport', 'luxury'],
    'Entry package required',
    'Host professionals, amateur players, and non-golf guests must use the official entry or package process.',
    'https://www.jamaicaproam.com/',
    'Destination golf tournament and hospitality week across Montego Bay championship courses.',
    'Verified island calendar',
    true
  ),
  (
    'mouttet-mile-st-catherine-2026',
    'Mouttet Mile',
    'Caymanas',
    'South-East',
    'St. Catherine',
    'Caymanas Park',
    '2026-12-05T12:00:00-05:00',
    'December 5, 2026',
    array['sport', 'culture'],
    'Ticket/pass likely',
    'Race-day admission, reserved areas, hospitality, food, or rum experiences may require a ticket or pass.',
    'https://mouttetmile.com/',
    'Premier one-mile horse-racing event at Caymanas Park with racing, fashion, food, and hospitality experiences.',
    'Verified island calendar',
    true
  )
on conflict (id) do update set
  title = excluded.title,
  city = excluded.city,
  region = excluded.region,
  parish = excluded.parish,
  venue = excluded.venue,
  start_date = excluded.start_date,
  date_label = excluded.date_label,
  vibes = excluded.vibes,
  price = excluded.price,
  ticket_requirement = excluded.ticket_requirement,
  official_url = excluded.official_url,
  description = excluded.description,
  source_label = excluded.source_label,
  is_published = excluded.is_published,
  updated_at = now();
